### PR TITLE
Basic/#1 create campaign

### PR DESCRIPTION
**Pull request by chlrbtlr30**
* Setup hardHat Prettier
* Create Template for initial contract

### CODE REVIEW

**Comment by JunsikChoi** [comment]
How about add `.env.example`? for dotenv template

**Comment by chlrbtlr30** [comment]
< Solidity prettier setup >
* Add below statement to vscode .settings.json
```
  "solidity.formatter": "prettier",
  "[solidity]": {
    "editor.defaultFormatter": "NomicFoundation.hardhat-solidity"
  },
```

**Comment by JunsikChoi** [comment]
> how about add overriding `.prettierrc.json`? 
Here's what i found from Nomic Foundations' vscode extension details
```
// .prettierrc.json
{
  "overrides": [
    {
      "files": "*.sol",
      "options": {
        "printWidth": 80,
        "tabWidth": 4,
        "useTabs": false,
        "singleQuote": false,
        "bracketSpacing": false,
        "explicitTypes": "preserve"
      }
    }
  ]
}

```

**Review by JunsikChoi — APPROVED** [review]
LGTM

**Review by chlrbtlr30 — COMMENTED** [review]
LGTM!

**Pull request merged**
